### ISSUE TITLE
Лучше всегда ставить {} в if'е

### ISSUE THREAD

**Issue by coursar** [corben-dallas/test#1]
https://github.com/corben-dallas/test/blob/f7924519308d824491c0bb011524cdfdef38af3f/src/js/lib.js#L7-L8

**Comment by corben-dallas** [comment]
https://github.com/corben-dallas/test/blob/09227b4dd6c9c5fa3363d9938da139d1ba2b2dac/src/js/lib.js#L7-L9

@coursar , исправлено

**Comment by coursar** [comment]
Если исправили, надо закрывать issue, желательно сразу коммитом
